# Generated by Django 4.2.18 on 2025-06-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archetype",
                    models.CharField(
                        choices=[
                            ("hoplite", "Hoplite"),
                            ("peltast", "Peltast"),
                            ("toxotes", "Toxotes"),
                            ("hippikon", "Hippikon"),
                            ("psilos", "Psilos"),
                            ("strategos", "Strategos"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("strength_bonus", models.IntegerField(default=0)),
                ("agility_bonus", models.IntegerField(default=0)),
                ("stamina_bonus", models.IntegerField(default=0)),
                ("morale_bonus", models.IntegerField(default=0)),
                ("intimidation_bonus", models.FloatField(default=0.0)),
                ("culture", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Armour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("defence", models.IntegerField()),
                ("weight", models.FloatField()),
                ("durability", models.IntegerField(default=100)),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("shoulders", "Shoulders"),
                            ("arms", "Arms"),
                            ("hands", "Hands"),
                            ("chest", "Chest"),
                            ("waist", "Waist"),
                            ("legs", "Legs"),
                            ("feet", "Feet"),
                            ("shield", "Shield"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "weapon_class",
                    models.CharField(
                        choices=[
                            ("sword", "Sword"),
                            ("spear", "Spear"),
                            ("axe", "Axe"),
                            ("bow", "Bow"),
                            ("javelin", "Javelin"),
                            ("sling", "Sling"),
                            ("dagger", "Dagger"),
                            ("mace", "Mace"),
                            ("staff", "Staff"),
                            ("polearm", "Polearm"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_damage", models.IntegerField()),
                ("max_damage", models.IntegerField()),
                ("weight", models.FloatField()),
                ("durability", models.IntegerField(default=100)),
                ("is_ranged", models.BooleanField(default=False)),
                ("range", models.IntegerField(default=1)),
                ("speed", models.FloatField(default=1.0)),
                ("crit_chance", models.FloatField(default=0.05)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("olympian", "Olympian Pantheon"),
                            ("orphic", "Orphic Mysteries"),
                            ("dionysian", "Dionysian Cult"),
                            ("heroic", "Hero Cults"),
                            ("isis", "Cult of Isis"),
                            ("mithraic", "Mithraic Mysteries"),
                            ("zoroastrian", "Zoroastrianism"),
                            ("christianity", "Christianity"),
                            ("islam", "Islam"),
                            ("judaism", "Judaism"),
                        ],
                        max_length=100,
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("health", models.IntegerField(default=100)),
                ("strength", models.IntegerField(default=10)),
                ("agility", models.IntegerField(default=10)),
                ("stamina", models.IntegerField(default=100)),
                ("morale", models.IntegerField(default=100)),
                ("loyalty", models.IntegerField(default=100)),
                (
                    "archetype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battle.archetype",
                    ),
                ),
                (
                    "arms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arms_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "chest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chest_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "equipped_weapon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battle.weapon",
                    ),
                ),
                (
                    "feet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feet_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "hands",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hands_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "legs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legs_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "shield",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shield_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "shoulders",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shoulders_armor",
                        to="battle.armour",
                    ),
                ),
                (
                    "waist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waist_armor",
                        to="battle.armour",
                    ),
                ),
            ],
        ),
    ]
