# Generated by Django 4.2.18 on 2025-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="facial_hair",
            field=models.CharField(
                choices=[(1, "bald"), (2, "short"), (3, "medium"), (4, "long")],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hairstyle",
            field=models.CharField(
                choices=[(1, "bald"), (2, "short"), (3, "medium"), (4, "long")],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="skin_tone",
            field=models.CharField(
                choices=[(1, "white"), (2, "tan"), (3, "black")],
                default=1,
                max_length=100,
            ),
        ),
    ]
