# Generated by Django 4.2.18 on 2025-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0002_character_facial_hair_character_hairstyle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="facial_hair",
            field=models.CharField(
                choices=[
                    ("Bald", "Bald"),
                    ("Short", "Short"),
                    ("Medium", "Medium"),
                    ("Long", "Long"),
                ],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="hairstyle",
            field=models.CharField(
                choices=[
                    ("Bald", "Bald"),
                    ("Short", "Short"),
                    ("Medium", "Medium"),
                    ("Long", "Long"),
                ],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="skin_tone",
            field=models.CharField(
                choices=[("White", "White"), ("Tan", "Tan"), ("Black", "Black")],
                default=1,
                max_length=100,
            ),
        ),
    ]
