# Generated by Django 4.2.18 on 2025-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0003_alter_character_facial_hair_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="max_health",
            field=models.IntegerField(default=100),
        ),
    ]
