# Generated by Django 4.2.18 on 2025-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_character_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="money",
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name="character",
            name="xp_points",
            field=models.FloatField(default=0),
        ),
    ]
