# Generated by Django 4.2.18 on 2025-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0006_character_level_character_money_character_xp_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="max_stamina",
            field=models.IntegerField(default=100),
        ),
    ]
