# Generated by Django 4.2.18 on 2025-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0007_character_max_stamina"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="focus",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="vitality",
            field=models.IntegerField(default=1),
        ),
    ]
